[build]
target = "thumbv7em-none-eabihf"

[target.thumbv7em-none-eabihf]
runner = "probe-run --chip nRF52833_xxAA"
rustflags = [ "-C", "linker=rust-lld", "-C", "link-arg=-Tlink.x" ]

[env]
DEFMT_LOG = "trace"
